# Generated by Django 4.1.2 on 2022-10-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='services',
            new_name='services_ids',
        ),
    ]
